DROP TABLE Employee24;

CREATE TABLE Employee24 (
    EMPNO NUMBER(5),
    ENAME VARCHAR2(50),
    JOB VARCHAR2(50),
    MANAGER_NO NUMBER(5),
    SAL NUMBER(10, 2),
    COMMISSION NUMBER(10, 2)
);

INSERT INTO Employee24 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION)
VALUES (1, 'John Doe', 'Manager', NULL, 5000, 1000);

INSERT INTO Employee24 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION)
VALUES (2, 'Jane Smith', 'Developer', 1, 4000, NULL);

INSERT INTO Employee24 (EMPNO, ENAME, JOB, MANAGER_NO, SAL, COMMISSION)
VALUES (3, 'Alice Johnson', 'Analyst', 1, 3500, 500);

SELECT * FROM Employee24;

DESC Employee24;